-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE SCHEMA IF NOT EXISTS staging
	AUTHORIZATION postgres;

CREATE TABLE IF NOT EXISTS staging."softcartDimDate"
(
    dateid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    date date NOT NULL,
    year integer NOT NULL,
    quarter smallint NOT NULL,
    quartername character varying(2) NOT NULL,
    month smallint NOT NULL,
    monthname character varying(10) NOT NULL,
    weekday smallint NOT NULL,
    weekdayname character varying(10) NOT NULL,
    day smallint NOT NULL,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimCategory"
(
    categoryid integer NOT NULL,
    category character varying(15) NOT NULL,
    subcategory character varying(15) NOT NULL,
    PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimItem"
(
    itemid integer NOT NULL,
    item character varying NOT NULL,
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimCountry"
(
    countryid integer NOT NULL,
    country character varying(50) NOT NULL,
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS staging."softcartFactSales"
(
    orderid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    dateid integer NOT NULL,
    categoryid integer NOT NULL,
    itemid integer NOT NULL,
    countryid integer NOT NULL,
    price money NOT NULL,
    PRIMARY KEY (orderid)
);

ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD CONSTRAINT dateid FOREIGN KEY (dateid)
    REFERENCES staging."softcartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD CONSTRAINT categoryid FOREIGN KEY (categoryid)
    REFERENCES staging."softcartDimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD CONSTRAINT itemid FOREIGN KEY (itemid)
    REFERENCES staging."softcartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD CONSTRAINT countryid FOREIGN KEY (countryid)
    REFERENCES staging."softcartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;